### ISSUE TITLE
Regarding feature extraction for other datasets from raw inputs

### ISSUE THREAD

**Issue by iyamabhishek** [A2Zadeh/Social-IQ#3]
Hi Amir,

I want to extract audio, video, and text features (similar to what is used in Social-IQ) for other multimodal datasets. Can you please guide me on how the video (DenseNet161 scene embeddings), audio (COVAREP), and the text features (BERT embeddings) were extracted?

Example: To extract the features for the above three modalities for CMU-MOSEI, what steps should I take?

Thank you!

**Comment by A2Zadeh** [comment]
Hello @iyamabhishek. Happy to help. BERT extractions are done using the hugging-face implementation of the BERT model. There is a tokenization step that needs to be modified since if a word gets split, the timestamp should also be split (or simply tokens averaged). COVAREP has a github with examples on how to extract audio features @ 100 Hz; you can get the audio from video using ffmpeg. Finally, DenseNet also has online implementations. Firstly you need to extract the frames from a video @ 30 Hz, and then feed that into the DenseNet extractor. Subsequently, you can get the last layer (which I believe is actually a max-pool layer, as opposed to the usual fc layer. I flattened it and treated it as a fc output).

**Comment by iyamabhishek** [comment]
Awesome! Thank you for the quick reply! 
I will try these steps out and revert back if I face any issues.

**Comment by A2Zadeh** [comment]
@iyamabhishek Please do.

**Comment by A2Zadeh** [comment]
@iyamabhishek I will close this issue for now, but I will keep on monitoring it.

**Comment by iyamabhishek** [comment]
Hi @A2Zadeh,

Thank you for your help so far! I have been able to sample the frames and extract the features from DenseNet161. My final vector looks like [2208, 7, 7]. In the Social-IQ paper 'last mean pooling layer' is mentioned. From what I understand for each 2208 _item_, you have [7,7] features, and you take the mean of [7, 7] for each 2208 _item_. Is this correct?

Secondly, if I have the words which are already segmented into timestamps, do I need to worry about the tokenization which BERT does? Because even if the word is split, the new words will fall in the same timestamp bucket.

**Comment by A2Zadeh** [comment]
@iyamabhishek you are correct on DenseNet! 

You are right. I just mentioned it so you are aware of what may happen during tokenization.

**Comment by iyamabhishek** [comment]
Thank you for confirming it!

**Comment by iyamabhishek** [comment]
Hi @A2Zadeh,

All the BERT based features have dimension 9216. If each word/token had dimension 768, then does it mean that you have 12 words for each sentence?

1. Am I correct in assuming the dimension to be 768?
2. How do you handle sentences with longer/shorter length because BERT also does tokenisation which might result in word splitting?
